package com.example.bankmember.applications;

import com.example.bankcommon.domain.Name;
import com.example.bankmember.applications.port.MemberCommandRepository;
import com.example.bankmember.applications.port.MemberQueryRepository;
import com.example.bankmember.domain.Member;
import com.example.bankmember.domain.MemberState;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public class FakeMemberRepository implements MemberCommandRepository, MemberQueryRepository {
    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<Member> members = new ArrayList<>();

    @Override
    public Member save(Member member) {

        if (member.getId() == null || member.getId() == 0) {
            Member newMember = Member.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .name(Name.newInstance(member.getName().getName()))
                    .role(member.getRole())
                    .state(member.getState())
                    .createdAt(member.getCreatedAt())
                    .modifiedAt(member.getModifiedAt())
                    .build();

            members.add(newMember);
            return newMember;
        }

        members.removeIf(m -> Objects.equals(m.getId(), member.getId()));
        members.add(member);
        return member;
    }

    @Override
    public Member getMember(String name) {
        return members.stream()
                .filter(member -> member.getName().isEquals(name))
                .findAny()
                .get();
    }

    @Override
    public Member getMember(String name, MemberState memberState) {
        return members.stream()
                .filter(member -> member.getName().isEquals(name) && member.getState().equals(MemberState.ACTIVITY))
                .findAny()
                .get();
    }
}